# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\"y\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x04type\x18\x02 \x01(\x0e\x32\t.TaskType\x12\x10\n\x08operand1\x18\x03 \x01(\x01\x12\x10\n\x08operand2\x18\x04 \x01(\x01\x12\x0f\n\x07timeout\x18\x05 \x01(\x05\x12\x17\n\x0fprocessing_time\x18\x06 \x01(\x05\"Z\n\nTaskResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1b\n\x06status\x18\x02 \x01(\x0e\x32\x0b.TaskStatus\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\x01\"?\n\x10WorkerProperties\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1f\n\x0c\x63\x61pabilities\x18\x02 \x03(\x0e\x32\t.TaskType*H\n\x08TaskType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\x0c\n\x08SUBTRACT\x10\x02\x12\x0c\n\x08MULTIPLY\x10\x03\x12\n\n\x06\x44IVIDE\x10\x04*H\n\nTaskStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06QUEUED\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\x08\n\x04\x44ONE\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKTYPE']._serialized_start=295
  _globals['_TASKTYPE']._serialized_end=367
  _globals['_TASKSTATUS']._serialized_start=369
  _globals['_TASKSTATUS']._serialized_end=441
  _globals['_TASK']._serialized_start=15
  _globals['_TASK']._serialized_end=136
  _globals['_TASKRESULT']._serialized_start=138
  _globals['_TASKRESULT']._serialized_end=228
  _globals['_WORKERPROPERTIES']._serialized_start=230
  _globals['_WORKERPROPERTIES']._serialized_end=293
# @@protoc_insertion_point(module_scope)
