# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x10task_distributor\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.task_distributor.TaskType\x12\x10\n\x08operand1\x18\x03 \x01(\x01\x12\x10\n\x08operand2\x18\x04 \x01(\x01\x12\x0f\n\x07timeout\x18\x05 \x01(\x05\x12\x17\n\x0fprocessing_time\x18\x06 \x01(\x05\"k\n\nTaskResult\x12\n\n\x02id\x18\x01 \x01(\t\x12,\n\x06status\x18\x02 \x01(\x0e\x32\x1c.task_distributor.TaskStatus\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\x01\"P\n\x10WorkerProperties\x12\n\n\x02id\x18\x01 \x01(\t\x12\x30\n\x0c\x63\x61pabilities\x18\x02 \x03(\x0e\x32\x1a.task_distributor.TaskType*;\n\x08TaskType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x0c\n\x08SUBTRACT\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x12\n\n\x06\x44IVIDE\x10\x03*;\n\nTaskStatus\x12\n\n\x06QUEUED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x08\n\x04\x44ONE\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x32\xa6\x01\n\x0fTaskDistributor\x12\x42\n\nSubmitTask\x12\x16.task_distributor.Task\x1a\x1c.task_distributor.TaskResult\x12O\n\x11PublishProperties\x12\".task_distributor.WorkerProperties\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKTYPE']._serialized_start=394
  _globals['_TASKTYPE']._serialized_end=453
  _globals['_TASKSTATUS']._serialized_start=455
  _globals['_TASKSTATUS']._serialized_end=514
  _globals['_TASK']._serialized_start=63
  _globals['_TASK']._serialized_end=201
  _globals['_TASKRESULT']._serialized_start=203
  _globals['_TASKRESULT']._serialized_end=310
  _globals['_WORKERPROPERTIES']._serialized_start=312
  _globals['_WORKERPROPERTIES']._serialized_end=392
  _globals['_TASKDISTRIBUTOR']._serialized_start=517
  _globals['_TASKDISTRIBUTOR']._serialized_end=683
# @@protoc_insertion_point(module_scope)
